name: Docs

concurrency:
  group: ci-docs-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"
      - "main"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx pydata-sphinx-theme myst-parser
      - name: Sphinx build
        working-directory: docs
        run: |
          make html
      - name: Link check
        working-directory: docs
        run: |
          make linkcheck
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build/html
