name: Test Self Hosted Runners
on: push
jobs:
  job1_cpu:
    runs-on: linux-amd64-cpu8
    container:
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-cuda11.8-mambaforge-ubuntu22.04
      env:
        DEFAULT_CONDA_ENV: legate
    steps:
      - name: Install dependencies
        run: |
          PATH=$PATH:/opt/conda/bin;
          mamba install  -c nvidia -c conda-forge -c legate -c "nvidia/label/cuda-11.8.0" cuda-runtime legate-core cunumeric scikit-learn scikit-build;
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          PATH=$PATH:/opt/conda/bin;
          pip install .
  job2_gpu:
    runs-on: linux-amd64-gpu-v100-latest-1
    container: # GPU jobs must run in a container
      image: nvidia/cuda:11.8.0-base-ubuntu22.04
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }} # GPU jobs must set this container env variable
    steps:
      - name: hello
        run: |
          echo "hello"
          nvidia-smi
